### ISSUE TITLE
`defaultPageBanner` in settings can't handle local urls

### ISSUE THREAD

**Issue by stdword** [yoyurec/logseq-banners-plugin#61]
Hello!
I have setting:
![image](https://user-images.githubusercontent.com/1984175/195211675-d0a29d32-21eb-4b40-86f2-a45958d84e92.png)

And the result is no banner on any page.

Console log:
![image](https://user-images.githubusercontent.com/1984175/195211690-5cd3ccc4-890b-4596-a06f-bedffc27d15b.png)

This is true: there is no such file. But I don't want to hardcode full path to my Logseq graph's folder.

PS same problem with `defaultJournalBanner`

**Comment by ireina7** [comment]
Only 2 options
- Put the image in the plugin's path `~/.logseq/plugins/logseq-banners-plugin/assets`. With this option, you can use relative path like `../assets/<img>`
- Just use full path.

p.s. In fact I suggest we can have relative path to logseq's `assets` fold rather than the plugin's `assets`.

**Comment by yoyurec** [comment]
fixed, check latest release
